const _role = [
  {
    name: '超级管理员',
    code: 'super_admin',
    description: '超级管理员',
    isSystem: true,
  },
  {
    name: '管理员',
    code: 'admin',
    description: '管理员',
  },
  {
    name: '用户',
    code: 'user',
    description: '用户',
  },
]
const _menu = [
  {
    name: 'Dashboard',
    path: 'dashboard',
    redirect: '/dashboard/workplace',
    type: 'DIRECTORY',
    component: '#',
    sort: 0,
    enabled: true,
    title: 'router.dashboard',
    icon: 'gauge',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'Workplace',
        path: 'workplace',
        redirect: null,
        type: 'MENU',
        component: 'views/Dashboard/Workplace',
        sort: 0,
        enabled: true,
        title: 'router.workplace',
        icon: 'monitor',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Analysis',
        path: 'analysis',
        redirect: null,
        type: 'MENU',
        component: 'views/Dashboard/Analysis',
        sort: 1,
        enabled: true,
        title: 'router.analysis',
        icon: 'chart-column',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'Authorization',
    path: 'authorization',
    redirect: '/authorization/user',
    type: 'DIRECTORY',
    component: '#',
    sort: 1,
    enabled: true,
    title: 'router.authorization',
    icon: 'lock',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,

    children: [
      {
        name: 'Department',
        path: 'department',
        redirect: null,
        type: 'MENU',
        component: 'views/Authorization/Department/Department',
        sort: 0,
        enabled: true,
        title: 'router.department',
        icon: 'building-2',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Dictionary',
        path: 'dictionary',
        redirect: null,
        type: 'MENU',
        component: 'views/Authorization/Dictionary/Dictionary',
        sort: 1,
        enabled: true,
        title: 'router.dictionary',
        icon: 'book',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'User',
        path: 'user',
        redirect: null,
        type: 'MENU',
        component: 'views/Authorization/User/User',
        sort: 2,
        enabled: true,
        title: 'router.userIdentity',
        icon: 'user',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Menu',
        path: 'menu',
        redirect: null,
        type: 'MENU',
        component: 'views/Authorization/Menu/Menu',
        sort: 3,
        enabled: true,
        title: 'router.menuManagement',
        icon: 'square-menu',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: true,
        noTagsView: false,
      },
      {
        name: 'Role',
        path: 'role',
        redirect: null,
        type: 'MENU',
        component: 'views/Authorization/Role/Role',
        sort: 4,
        enabled: true,
        title: 'router.role',
        icon: 'users-round',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'Personal',
    path: 'personal',
    redirect: '/persoanl/information',
    type: 'DIRECTORY',
    component: '#',
    sort: 2,
    enabled: true,
    title: 'router.personalCenter',
    icon: 'user',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'PersonalCenter',
        path: 'information',
        redirect: null,
        type: 'MENU',
        component: 'views/Personal/PersonalCenter/PersonalCenter',
        sort: 0,
        enabled: true,
        title: 'router.userInfo',
        icon: 'contact',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Message',
        path: 'message',
        redirect: null,
        type: 'MENU',
        component: 'views/System/Message/Message',
        sort: 0,
        enabled: true,
        title: 'router.message',
        icon: 'bell',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'System',
    path: 'system',
    redirect: '/system/userLog',
    type: 'DIRECTORY',
    component: '#',
    sort: 3,
    enabled: true,
    title: 'router.systemManagement',
    icon: 'settings',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'OnlineUser',
        path: 'onlineUser',
        redirect: null,
        type: 'MENU',
        component: 'views/System/OnlineUser/OnlineUser',
        sort: 0,
        enabled: true,
        title: 'router.onlineUser',
        icon: 'user',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Oss',
        path: 'oss',
        redirect: null,
        type: 'MENU',
        component: 'views/System/Oss/Oss',
        sort: 0,
        enabled: true,
        title: 'router.ossManagement',
        icon: 'file',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'FileList',
        path: 'fileList',
        redirect: null,
        type: 'MENU',
        component: 'views/System/File/FileList',
        sort: 0,
        enabled: true,
        title: 'router.fileManagement',
        icon: 'file-text',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Server',
        path: 'server',
        redirect: null,
        type: 'MENU',
        component: 'views/System/Server/Server',
        sort: 0,
        enabled: true,
        title: 'router.server',
        icon: 'monitor',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'DatabaseBackup',
        path: 'databaseBackup',
        redirect: null,
        type: 'MENU',
        component: 'views/System/DatabaseBackup/DatabaseBackup',
        sort: 0,
        enabled: true,
        title: 'router.databaseBackup',
        icon: 'database',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Notification',
        path: 'notification',
        redirect: null,
        type: 'MENU',
        component: 'views/System/Message/Notification',
        sort: 0,
        enabled: true,
        title: 'router.notification',
        icon: 'mail',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'UserLog',
        path: 'userLog',
        redirect: null,
        type: 'MENU',
        component: 'views/System/UserLog/UserLog',
        sort: 0,
        enabled: true,
        title: 'router.userLog',
        icon: 'ticket',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'AuditLog',
        path: 'auditLog',
        redirect: null,
        type: 'MENU',
        component: 'views/System/AuditLog/AuditLog',
        sort: 1,
        enabled: true,
        title: 'router.auditLog',
        icon: 'document',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
]

const _permission = [
  {
    name: '新增',
    code: 'add',
    resource: 'department',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'department',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'department',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'department',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'department',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'user',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'user',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'user',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'user',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '更新',
    code: 'update',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '刷新菜单',
    code: 'refresh',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'role',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'role',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'role',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'role',
    type: 'button',
  },
  {
    name: '生成种子',
    code: 'seed',
    resource: 'role',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '上传',
    code: 'add',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'userLog',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'userLog',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'auditLog',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'server',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'databaseBackup',
    type: 'button',
  },
  {
    name: '更新配置',
    code: 'update',
    resource: 'databaseBackup',
    type: 'button',
  },
  {
    name: '立即备份',
    code: 'run',
    resource: 'databaseBackup',
    type: 'button',
  },
  {
    name: '下载',
    code: 'download',
    resource: 'databaseBackup',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'databaseBackup',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'onlineUser',
    type: 'button',
  },
  {
    name: '强制下线',
    code: 'kick',
    resource: 'onlineUser',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'message',
    type: 'button',
  },
  {
    name: '发送',
    code: 'send',
    resource: 'notification',
    type: 'button',
  },
]

export { _menu, _permission, _role }
