const _role = [
  {
    name: '超级管理员',
    code: 'super_admin',
    description: '超级管理员',
    isSystem: true,
  },
  {
    name: '管理员',
    code: 'admin',
    description: '管理员',
  },
  {
    name: '用户',
    code: 'user',
    description: '用户',
  },
];
const _menu = [
  {
    name: 'Dashboard',
    path: 'dashboard',
    redirect: '/dashboard/workplace',
    type: 0,
    component: '#',
    sort: 0,
    enabled: true,
    title: 'router.dashboard',
    icon: 'ant-design:dashboard-outlined',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'Workplace',
        path: 'workplace',
        redirect: null,
        type: 1,
        component: 'views/Dashboard/Workplace',
        sort: 0,
        enabled: true,
        title: 'router.workplace',
        icon: 'mdi:facebook-workplace',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Analysis',
        path: 'analysis',
        redirect: null,
        type: 1,
        component: 'views/Dashboard/Analysis',
        sort: 1,
        enabled: true,
        title: 'router.analysis',
        icon: 'uil:statistics',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'Authorization',
    path: 'authorization',
    redirect: '/authorization/user',
    type: 0,
    component: '#',
    sort: 1,
    enabled: true,
    title: 'router.authorization',
    icon: 'fluent-mdl2:permissions',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,

    children: [
      {
        name: 'Department',
        path: 'department',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Department/Department',
        sort: 0,
        enabled: true,
        title: 'router.department',
        icon: 'mingcute:department-line',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Dictionary',
        path: 'dictionary',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Dictionary/Dictionary',
        sort: 1,
        enabled: true,
        title: 'router.dictionary',
        icon: 'qlementine-icons:dictionary-16',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'User',
        path: 'user',
        redirect: null,
        type: 1,
        component: 'views/Authorization/User/User',
        sort: 2,
        enabled: true,
        title: 'router.userIdentity',
        icon: 'solar:user-linear',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Menu',
        path: 'menu',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Menu/Menu',
        sort: 3,
        enabled: true,
        title: 'router.menuManagement',
        icon: 'lucide:square-menu',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: true,
        noTagsView: false,
      },
      {
        name: 'Role',
        path: 'role',
        redirect: null,
        type: 1,
        component: 'views/Authorization/Role/Role',
        sort: 4,
        enabled: true,
        title: 'router.role',
        icon: 'oui:app-users-roles',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'Personal',
    path: 'personal',
    redirect: '/persoanl/information',
    type: 0,
    component: '#',
    sort: 2,
    enabled: true,
    title: 'router.personalCenter',
    icon: 'vi-ant-design:user-outlined',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'PersonalCenter',
        path: 'information',
        redirect: null,
        type: 1,
        component: 'views/Personal/PersonalCenter/PersonalCenter',
        sort: 0,
        enabled: true,
        title: 'router.userInfo',
        icon: 'fluent-mdl2:contact-info',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: 'System',
    path: 'system',
    redirect: '/system/userLog',
    type: 0,
    component: '#',
    sort: 3,
    enabled: true,
    title: 'router.systemManagement',
    icon: 'grommet-icons:system',
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: 'UserList',
        path: 'userList',
        redirect: null,
        type: 1,
        component: 'views/System/UserList/UserList',
        sort: 0,
        enabled: true,
        title: 'router.userManagement',
        icon: 'solar:user-linear',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'OnlineUser',
        path: 'onlineUser',
        redirect: null,
        type: 1,
        component: 'views/System/OnlineUser/OnlineUser',
        sort: 0,
        enabled: true,
        title: 'router.onlineUser',
        icon: 'solar:user-linear',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'Oss',
        path: 'oss',
        redirect: null,
        type: 1,
        component: 'views/System/Oss/Oss',
        sort: 0,
        enabled: true,
        title: 'router.ossManagement',
        icon: 'eva:file-outline',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'FileList',
        path: 'fileList',
        redirect: null,
        type: 1,
        component: 'views/System/File/FileList',
        sort: 0,
        enabled: true,
        title: 'router.fileManagement',
        icon: 'eva:file-outline',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: 'UserLog',
        path: 'userLog',
        redirect: null,
        type: 1,
        component: 'views/System/UserLog/UserLog',
        sort: 0,
        enabled: true,
        title: 'router.userLog',
        icon: 'octicon:log-24',
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
];

const _permission = [
  {
    name: '新增',
    code: 'add',
    resource: 'department',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'department',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'department',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'department',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'department',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'dictionary',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'user',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'user',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'user',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'user',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '更新',
    code: 'update',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '刷新菜单',
    code: 'refresh',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '种子数据',
    code: 'seed',
    resource: 'menu',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'role',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'role',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'role',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'role',
    type: 'button',
  },
  {
    name: '生成种子',
    code: 'seed',
    resource: 'role',
    type: 'button',
  },
  {
    name: '新增',
    code: 'add',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '编辑',
    code: 'update',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'personal',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '上传',
    code: 'add',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'fileList',
    type: 'button',
  },
  {
    name: '查看',
    code: 'view',
    resource: 'userLog',
    type: 'button',
  },
  {
    name: '删除',
    code: 'delete',
    resource: 'userLog',
    type: 'button',
  },
];

export { _menu, _permission, _role };
