// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'src/prisma/schema/schema.prisma',
  migrations: {
    path: 'src/prisma/migrations',
    seed: 'tsx src/prisma/seed.ts', // seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    // url: process.env['DATABASE_URL'],
    url: env('PG_DATABASE_URL'),
  },
});
